config/routes.rb
Rails.application.routes.draw do
  resources :episodes
  resources :seasons
  resources :films
  resources :generes

  root "films#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :film
  has_many :episodes

  validates :number, :presence => true
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: %i[ show edit update destroy ]

  # GET /seasons or /seasons.json
  def index
    @seasons = Season.all
    @seasons = @seasons.joins(:film).where(:film => {:id => params[:film_id]}) if params[:film_id]
		@seasons = @seasons.where(["name LIKE :filter", :filter => ("%" + params[:filter] + "%")]) unless params[:filter].blank?
   #esto es para la filtracion en el index de series cuando quiero ver sus temporadas

   @seasons = @seasons.joins(:espisode).where(:espisode => {:id => params[:espisode_id]}) if params[:espisode_id]
   @seasons = @seasons.where(["number LIKE :filte", :filte => ("%" + params[:filte] + "%")]) unless params[:filte].blank?
  #esto es para la filtracion en el index de episodios cuando quiero ver sus temporadas


  end




  # GET /seasons/1 or /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons or /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: "Season was successfully created." }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1 or /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: "Season was successfully updated." }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1 or /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: "Season was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def season_params
      params.require(:season).permit(:number, :begins_at, :film_id)
    end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_with(model: season) do |form| %>
  <% if season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
        <% season.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :begins_at %>
    <%= form.datetime_select :begins_at %>
  </div>

  <div class="field">
    <%= form.label :film_id %>
    <%= form.collection_select(:film_id, Film.all,:id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Editing Season</h1>

<%= render 'form', season: @season %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Temporadas</h1>

<form method="input" action="/films">
  Buscar por serie: <input type= integer name="filter" />  
  <input type="submit" />
</form><br>



<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Lanzamineto</th>
      <th><th>
      <th>Serie</th>
      <th><th>
      <th>Minutos</th>
      <th><th>
      <th>Episodios</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>

    <% @seasons.each do |season| %>
     
        <tr>
          <td><%= season.number %></td>
          <td><%= season.begins_at %></td>
          <td><td>
          <!td><%= season.film.name %></td>
          <td><td>
          <td><%= season.episodes.sum(:minute) %></td>
          <td><td>
          <td>
            <% if season.episodes.count == 0 %>
              <%= season.episodes.count %>
            <% else %>
              <%= link_to season.episodes.count, episodes_path(:season_id => season.id) %>
            <% end %>
          <td>
          <td><%= link_to 'Show', season %></td>
          <td><%= link_to 'Edit', edit_season_path(season) %></td>
          <td><%= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
     
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Season', new_season_path %>

app/views/seasons/new.html.erb
<h1>New Season</h1>

<%= render 'form', season: @season %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @season.number %>
</p>

<p>
  <strong>Begins at:</strong>
  <%= @season.begins_at %>
</p>

<p>
  <strong>Film:</strong>
  <%= @season.film_id %>
</p>

<%= link_to 'Edit', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path %>