config/routes.rb
Rails.application.routes.draw do
  resources :episodes
  resources :seasons
  resources :films
  resources :generes

  root "films#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :season

  validates :title, :presence => true
  validates :minute, :presence => true
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: %i[ show edit update destroy ]

  # GET /episodes or /episodes.json
  def index
    @episodes = Episode.all
    @episodes = @episodes.joins(:season).where(:season => {:id => params[:season_id]}) if params[:season_id]
		@episodes = @episodes.where(["name LIKE :filter", :filter => ("%" + params[:filter] + "%")]) unless params[:filter].blank?
   #para el index de temporada cuando quiero ver sus episodios
    

   @episodes = @episodes.where(["title LIKE :fil", :fil => ("%" + params[:fil] + "%")]) unless params[:fil].blank?

  end

  # GET /episodes/1 or /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes or /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: "Episode was successfully created." }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1 or /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: "Episode was successfully updated." }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1 or /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: "Episode was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def episode_params
      params.require(:episode).permit(:numer, :title, :emmited_at, :minute, :season_id)
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_with(model: episode) do |form| %>
  <% if episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
        <% episode.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :numer %>
    <%= form.number_field :numer %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :emmited_at %>
    <%= form.datetime_select :emmited_at %>
  </div>

  <div class="field">
    <%= form.label :minute %>
    <%= form.number_field :minute %>
  </div>

  <div class="field">
    <%= form.label :season_id %>
    <%= form.collection_select(:season_id, Season.all,:id, :number) %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodios</h1>

<form method="input" action="/seasons">
  Buscar por temporada: <input type=integer name="filte" />  
  <input type="submit" />
</form><br>

<form method="input" action="/episodes">
  Buscar por nombre de episodio: <input type="text" name="fil" />  
  <input type="submit" />
</form><br>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Titulo</th>
      <th>Rodaje</th>
      <th>Minutos</th>
      <th>Temporada</th>
      <th>Serie</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.numer %></td>
        <td><%= episode.title %></td>
        <td><%= episode.emmited_at %></td>
        <td><%= episode.minute %></td>
        <td><%= episode.season_id %></td>
        <td><%= episode.season.film.name %></td>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numer:</strong>
  <%= @episode.numer %>
</p>

<p>
  <strong>Title:</strong>
  <%= @episode.title %>
</p>

<p>
  <strong>Emmited at:</strong>
  <%= @episode.emmited_at %>
</p>

<p>
  <strong>Minute:</strong>
  <%= @episode.minute %>
</p>

<p>
  <strong>Season:</strong>
  <%= @episode.season_id %>
</p>

<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>