config/routes.rb
Rails.application.routes.draw do
  resources :episodes
  resources :seasons
  resources :films
  resources :generes

  root "films#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genere.rb
class Genere < ApplicationRecord
    has_many :film

    validates :name, :presence => true, :uniqueness => true
end

app/controllers/generes_controller.rb
class GeneresController < ApplicationController
  before_action :set_genere, only: %i[ show edit update destroy ]

  # GET /generes or /generes.json
  def index
    @generes = Genere.all
  end

  # GET /generes/1 or /generes/1.json
  def show
  end

  # GET /generes/new
  def new
    @genere = Genere.new
  end

  # GET /generes/1/edit
  def edit
  end

  # POST /generes or /generes.json
  def create
    @genere = Genere.new(genere_params)

    respond_to do |format|
      if @genere.save
        format.html { redirect_to @genere, notice: "Genere was successfully created." }
        format.json { render :show, status: :created, location: @genere }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genere.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generes/1 or /generes/1.json
  def update
    respond_to do |format|
      if @genere.update(genere_params)
        format.html { redirect_to @genere, notice: "Genere was successfully updated." }
        format.json { render :show, status: :ok, location: @genere }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genere.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generes/1 or /generes/1.json
  def destroy
    @genere.destroy
    respond_to do |format|
      format.html { redirect_to generes_url, notice: "Genere was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genere
      @genere = Genere.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genere_params
      params.require(:genere).permit(:name)
    end
end

app/helpers/generes_helper.rb
module GeneresHelper
end

app/views/generes/_form.html.erb
<%= form_with(model: genere) do |form| %>
  <% if genere.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genere.errors.count, "error") %> prohibited this genere from being saved:</h2>

      <ul>
        <% genere.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/generes/edit.html.erb
<h1>Editing Genere</h1>

<%= render 'form', genere: @genere %>

<%= link_to 'Show', @genere %> |
<%= link_to 'Back', generes_path %>

app/views/generes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Generos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Nro de series</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @generes.each do |genere| %>
      <tr>
        <td><%= genere.name %></td>
        <td>
          <% if genere.film.count == 0 %>
            <%= genere.film.count %>
          <% else %>
            <%= link_to genere.film.count, films_path(:genere_id => genere.id) %>
          <% end %>
			  <td>
        <td><%= link_to 'Show', genere %></td>
        <td><%= link_to 'Edit', edit_genere_path(genere) %></td>
        <td><%= link_to 'Destroy', genere, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Genere', new_genere_path %>

app/views/generes/new.html.erb
<h1>New Genere</h1>

<%= render 'form', genere: @genere %>

<%= link_to 'Back', generes_path %>

app/views/generes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @genere.name %>
</p>

<%= link_to 'Edit', edit_genere_path(@genere) %> |
<%= link_to 'Back', generes_path %>